### ISSUE TITLE
IPFS daemon

### ISSUE THREAD

**Issue by donvex** [ngngardner/dart_ipfs_client#2]
Hello 

```
sendMessage() async {
    print('-------------1');
    var ipfs = Ipfs(url: 'http://10.0.2.2:8080');
    print('-------------2');
    var addRes = await ipfs.add(utf8.encode('Hello World!'));
    print('-------------3');

    // var catRes = await ipfs.cat(addRes.body.hash);

    //print(catRes.body.toJson());
  }
```
when i call this method **sendMessage()** I only have in my consol 
----------1
----------2

Erreur in the console:
`[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: SocketException: OS Error: Connection timed out, errno = 110, address = 10.0.2.2, port = 41004`
**don't have port 41004**
**the last print is not showing**

Please help me understand the issues 

thank you

**Comment by ngngardner** [comment]
Can you confirm the API is accessible from your environment?

`curl -X POST "http://10.0.2.2:8080/api/v0/id"`
